language: node_js
node_js:
  - 14  # 使用 nodejs LTS v14
branches:
  only:
    - main # 只监控 main 的 branch
cache:
  npm
install:
  - yarn
script:
  - hexo clean
  - hexo generate # generate static files
deploy: # 根据个人情况，这里会有所不同
  provider: pages
  skip_cleanup: true # 构建完成后不清除
  token: $GH_TOKEN # travis设置的 token
  keep_history: true # 保存历史
  on:
    branch: main # hexo 站点源文件所在的 branch
  local_dir: public
  # target_branch: gh-pages # 存放生成站点文件的 branch
